### ISSUE TITLE
The plugin does not work properly with $.noConflict() option

### ISSUE THREAD

**Issue by rroman81** [filamentgroup/jQuery-Equal-Heights#13]
The plugin structure needs to change to take advantage of immediate functions in order to protect $ scope as per best practice, [basic plugin creation](http://learn.jquery.com/plugins/basic-plugin-creation/).

**Comment by zachleat** [comment]
Unfortunately this repository has been moved into an unmaintained state and as such all open issues and pull requests will now be closed. The content there-in has been deprecated in favor of the [Equal Heights section on our layout-patterns repo](http://filamentgroup.github.io/layout-patterns/columns/#equalheights).
