### ISSUE TITLE
seems to work only for a single instances?

### ISSUE THREAD

**Issue by emage** [filamentgroup/jQuery-Equal-Heights#15]
I want to have two  container with its child set to equal height.  Seems only the first one works.  If i take off the first one, the 2nd works.

Cant have multiple i guess.

**Comment by zachleat** [comment]
Unfortunately this repository has been moved into an unmaintained state and as such all open issues and pull requests will now be closed. The content there-in has been deprecated in favor of the [Equal Heights section on our layout-patterns repo](http://filamentgroup.github.io/layout-patterns/columns/#equalheights).
