### ISSUE TITLE
Run after AJAX content is loaded

### ISSUE THREAD

**Issue by since1976** [filamentgroup/jQuery-Equal-Heights#6]
I'm trying to get this to work alongside using your awesome Ajax-Include-Pattern, but can't get it to calculate the correct height. I'm guessing that it is failing because the Equal Height code can't see the AJAX inserted code. How would I go about getting this to run once the AJAX has inserted the correct content?

``` javascript
$(document).ready(function() {

    // Prevent world from ending on any href="#" a tags
    $('a[href="#"]').click(function(event) {
        event.preventDefault();
    });
    $("[data-append],[data-replace],[data-after],[data-before]").ajaxInclude();
    $('.mega-menu').equalHeights(false);
});
```

**Comment by zachleat** [comment]
Unfortunately this repository has been moved into an unmaintained state and as such all open issues and pull requests will now be closed. The content there-in has been deprecated in favor of the [Equal Heights section on our layout-patterns repo](http://filamentgroup.github.io/layout-patterns/columns/#equalheights).
